server:
  port: 8765

spring:
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://security
          predicates:
            - Path=/security/**
          filters:
            - RewritePath=/security(?<segment>/?.*), $\{segment}
            - TokenPreFilter
            - name: Hystrix
              args:
                name: security-service-filter
                fallbackuri: forward:/orderFallBack
        - id: user-service
          uri: lb://user
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}
            - TokenPreFilter
            - name: Hystrix
              args:
                name: user-service-filter
                fallbackuri: forward:/orderFallBack
        - id: hotel-service
          uri: lb://hotel
          predicates:
            - Path=/hotel-service/**
          filters:
            - RewritePath=/hotel-service(?<segment>/?.*), $\{segment}
            - TokenPreFilter
            - name: Hystrix
              args:
                name: hotel-service-filter
                fallbackuri: forward:/orderFallBack
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
