server:
  port: 8765

spring:
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://security
          predicates:
            - Path=/security/**,/api-docs/**
          filters:
            - name: RewritePath
              args:
                regexp: /security(?<segment>/?.*)
                replacement: $\{segment}
            - name: TokenPreFilter
            - name: Hystrix
              args:
                name: fallbackCommand
                fallbackUri: forward:/fallback/message
        - id: user-service
          uri: lb://user
          predicates:
            - Path=/user-service/**,/api-docs/**
          filters:
            - name: RewritePath
              args:
                regexp: /user-service(?<segment>/?.*)
                replacement: $\{segment}
            - name: TokenPreFilter
            - name: Hystrix
              args:
                name: fallbackCommand
                fallbackUri: forward:/fallback/message
        - id: hotel-service
          uri: lb://hotel
          predicates:
            - Path=/hotel-service/**,/api-docs/**
          filters:
            - name: RewritePath
              args:
                regexp: /hotel-service(?<segment>/?.*)
                replacement: $\{segment}
            - name: TokenPreFilter
            - name: Hystrix
              args:
                name: fallbackCommand
                fallbackUri: forward:/fallback/message
        - id: wallet-service
          uri: lb://wallet
          predicates:
            - Path=/api-docs/**
          filters:
            - RewritePath=/security(?<segment>/?.*), $\{segment}
            - TokenPreFilter
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG

springdoc:
  swagger-ui:
    urls:
      - url: /user/api-docs
        name: "User service"
      - url: /hotel/api-docs
        name: "Hotel service"
      - url: /wallet/api-docs
        name: "Wallet service"
      - url: /security/api-docs
        name: "Security service"
