server:
  port: 8765

spring:
  cloud:
    gateway:
      routes:
        - id: security-service
          uri: lb://security
          predicates:
            - Path=/security/**
          filters:
            - RewritePath=/security(?<segment>/?.*), $\{segment}
            - TokenPreFilter
        - id: user-service
          uri: lb://user
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}
            - TokenPreFilter
        - id: hotel-service
          uri: lb://hotel
          predicates:
            - Path=/hotel-service/**
          filters:
            - RewritePath=/hotel-service(?<segment>/?.*), $\{segment}
            - TokenPreFilter
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG


